# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sai Soundararaj
email: saip@outlook.com
description: >
  Human, Entrepreneur, Deep Learning Enthusiast
logo: "/assets/images/photo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://saiprashanths.github.io/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Sai Soundararaj'
bio: >
  Human, Entrepreneur, Deep Learning Enthusiast
author_image: "/assets/images/photo.jpg"
twitter_username: 
github_username:  saiprashanths

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

#Other
highlighter: pygments
encoding: utf-8
